Target fixes and change event generation
shipa-corp/ketch pull request #167
Opened 2021-10-16 15:27 UTC by koncar

# Description

Create dedicated structs for generated Canary events

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Testing

- [ ] New tests were added with this PR that prove my fix is effective or that my feature works (describe below this bullet)
- [ ] This change requires no testing (i.e. documentation update)

## Documentation

- [ ] All added public packages, funcs, and types have been documented with doc comments
- [ ] I have commented my code, particularly in hard-to-understand areas

## Final Checklist:

- [ ] I followed standard [GitHub flow](https://guides.github.com/introduction/flow/) guidelines
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

2021-10-20 16:42 UTC, stinkyfingers commented on internal/api/v1beta1/app_types.go
> +	return fmt.Sprintf("%s - Canary for app %s | version %d - %s", c.Name, c.AppName, c.DeploymentVersion, c.Description)
I'd probably make `"%s - Canary for app %s | version %d - %s"`. Not a huge concern. Same with the NextStepEvents and ChangeEvents below.

2021-10-20 16:43 UTC, stinkyfingers approved these changes
Looks good to me.

2021-10-21 14:46 UTC, aleksej-paschenko requested changes

2021-10-21 14:46 UTC, aleksej-paschenko commented on internal/api/v1beta1/app_types.go
> +	_, err = fmt.Sscanf(split[1], " Step: %d | Source version: %d | Dest version: %d | Source weight: %d | Dest weight: %d", &event.Step, &event.VersionSource, &event.VersionDest, &event.WeightSource, &
With @koncar we agreed on using an event's annotations to store this information instead of parsing it

2021-10-26 13:37 UTC, merged