[SHIPA-1457] Combine App Update, Create and Deploy
shipa-corp/ketch pull request #87
Opened 2021-05-21 15:33 UTC by murphybytes

# Description

Previously deploying an app with Ketch required two separate steps for creating an app and deploying an app.  The PR combines those operations into one.  

- Combining the operations introduced a lot of complexity regarding the number of flags, which were required, and how they were validated. We address this problem by introducing the idea of a change set, where we detect which flags have been changed and use them to perform app update operations before we deploy the app. 
- We added retry functionality to address eventually consistent k8s mutations of App CRD's. 
- The math on the Canary deploy was incorrect and was fixed.
- App create reconciliation events were failing due to lack of even permissions in the Ketch controller.  This has been fixed.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (documentation addition or typo, file relocation)

## Testing

- [x] New tests were added with this PR that prove my fix is effective or that my feature works (describe below this bullet)
- [ ] This change requires no testing (i.e. documentation update)

## Documentation

- [x] All added public packages, funcs, and types have been documented with doc comments
- [x] I have commented my code, particularly in hard-to-understand areas

## Final Checklist:

- [ ] I followed standard [GitHub flow](https://guides.github.com/introduction/flow/) guidelines
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

## Additional Information (omit if empty)

Please include anything else relevant to this PR that may be useful to know.

2021-05-21 17:07 UTC, stinkyfingers reviewed
Any chance us noobs can set up a time for a quick walk-through/demo? I've got a couple small questions. The code seems solid, but I'd like to parlay this PR into an education.

2021-05-21 17:07 UTC, stinkyfingers commented on internal/utils/labels.go
> +package utils
Yas!

2021-05-21 17:07 UTC, stinkyfingers commented on internal/deploy/validations.go
> +type statusError struct {
It seems like it might be worthwhile to share this error formatting with other packages. What do you think?

2021-05-21 17:07 UTC, stinkyfingers commented on internal/deploy/parameters.go
> +	if maximumSteps%steps != 0 {
Why is this the case? I assume I'm just not grokking what steps are.

2021-05-24 14:44 UTC, stinkyfingers approved these changes

2021-05-25 10:05 UTC, aleksej-paschenko requested changes
looks awesome!

2021-05-25 10:05 UTC, aleksej-paschenko commented on internal/deploy/deploy.go
> +		return errors.Wrap(err, "deploy from image failed[")
let's add eyes to that smile `:[`?

2021-05-25 14:49 UTC, murphybytes commented on internal/deploy/deploy.go
> +	var platform ketchv1.Platform
All references to platform will be removed in the second part of this feature when we integrate buildpacks.

2021-05-26 13:42 UTC, aleksej-paschenko approved these changes

2021-05-26 13:51 UTC, merged